![[Pasted image 20240527182437.png]]

* Error : 메모리 부족, 심각한 시스템 오류. 애플리케이션에서 복구 불가한 예외. 잡으려 하면 안됨
* Exception : 체크 예외 
	* 개발자가 명시적으로 체크해줘야함. 그렇지 않으면 컴파일 오류
	* 장점) 컴파일 통해 문제 잡아줘서 개발 실수 누락하지 않도록 해줌
	* 단점) 번거로움
* RuntimeException : 컴파일러가 체크하지 않는 언체크 예외.
	* 개발자가 명시적으로 처리하지 않아도 됨.
	* 장점) 신경쓰고 싶지 않은 예외 무시 가능.
	* 단점) 개발자 실수로 예외 누락 가능

* 상위 오류가 하위 예외까지 잡음. Exception 부터 잡으면 됨!

![[Pasted image 20240527182956.png]]
* main 밖으로 예외를 던지면 예외 로그 출력하며 시스템 종료.

* `throws` : 예외 밖으로 던짐
* `throw` : 예외 발생시키는 것

#### 현대 개발에서 체크 예외 사용하지 않음.

### 정상 흐름과 예외 흐름 섞여있음 ➡️ 에러 코드 분리
```java
package exception.ex2;

public class NetworkClientExceptionV2 extends Exception {

    private String errorCode;

    public NetworkClientExceptionV2(String errorCode, String message) {
        super(message);

        this.errorCode = errorCode;
    }

    public String getErrorCode() {
        return errorCode;
	}

}
```

### ➡️ 정상, 예외 흐름 분리 : try~catch
```java
 package exception.ex2;
 public class NetworkServiceV2_3 {

     public void sendMessage(String data) {
         String address = "http://example.com";

         NetworkClientV2 client = new NetworkClientV2(address);
         client.initError(data);

	try {  
		client.connect(); 
		client.send(data); 
		client.disconnect(); //예외 발생시 무시
	} catch (NetworkClientExceptionV2 e) {  
		System.out.println("[오류] 코드: " + e.getErrorCode() + ", 메시지: " +
	e.getMessage());
	}

	}
}
```

### ➡️ 리소스 반환 문제
```java
 public class NetworkServiceV2_4 {

     public void sendMessage(String data) {
         String address = "http://example.com";

         NetworkClientV2 client = new NetworkClientV2(address);
         client.initError(data);

         try {
             client.connect();
             client.send(data);

		} catch (NetworkClientExceptionV2 e) {  
			System.out.println("[오류] 코드: " + e.getErrorCode() + ", 메시지: " +
			 e.getMessage());
         }
         
         client.disconnect(); // 반드시 호출한다는 보장 불가
     }

}
```

### ➡️ finally
* finally 는 어떤 경우라도 반드시 호출
```java
try {  
//정상 흐름

} catch { 
//예외 흐름 

} finally {
//반드시 호출해야 하는 마무리 흐름 

}
```


# 예외 계층
![[Pasted image 20240527214149.png]]
* 특정 예외 잡아 처리할지 / 함께 잡을지로 선택 ➡️ 각각 로직 처리 가능


# 실무 예외 처리 방안
* 처리할 수 없는 예외
	* 시스템 오류 : 상대 nw 서버 문제 발생, db 서버 문제 발생, 앺플리케이션 연결 오류 등 
		➡️ 오류 메세지 보여주고. 내부 개발자 인지위한 로그 남기기
* 체크 예외의 부담
	* 처리할 수 없는 예외 많아지고(라이브러리..), 프로그램 복잡해지며 체크 예외 사용의 부담
	* 체크 예외 사용 시나리오
		![[Pasted image 20240527215220.png]]
		* 모든 예외를 던지는 최악의 수 : 중요한 체크 예외를 놓침

* 언체크 예외 사용 시나리오 
	![[Pasted image 20240527215854.png]]
	➡️ 해결할 수 없는 건 예외 공통 처리할 수 있는 곳에서 오류 및 로그 처리.

# try-with-resources
* AutoCloseable 인터페이스 구현
* Try with resources 구문 사용
	```java
	try (Resource resource = new Resource()) { 
		// 리소스를 사용하는 코드
	}
	```
	
```java
public class NetworkClientV5 implements AutoCloseable {

     private final String address;
     public boolean connectError;
     public boolean sendError;

     public NetworkClientV5(String address) {
         this.address = address;
	}

     public void connect() {
         if (connectError) {
			throw new ConnectExceptionV4(address, address + " 서버 연결 실패"); 
		 }
		 System.out.println(address + " 서버 연결 성공"); 
	}

    public void send(String data) {
        if (sendError) {
			throw new SendExceptionV4(data, address + " 서버에 데이터 전송 실패: " + data);
		}
		System.out.println(address + " 서버에 데이터 전송: " + data); 
	}

	public void disconnect() { 
		System.out.println(address + " 서버 연결 해제");
	}

    public void initError(String data) {
        if (data.contains("error1")) {
            connectError = true;
        }

        if (data.contains("error2")) {
            sendError = true;
		} 
	}

    @Override    
    public void close() {
        System.out.println("NetworkClientV5.close");
        disconnect();
    }

}
```